# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField(blank=True)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Everyday', 'Everyday')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('sessionKey', models.CharField(max_length=50)),
                ('userType', models.CharField(choices=[('Participant', 'Participant'), ('Staff', 'Staff'), ('Admin', 'Admin'), ('Family/Friends', 'Family/Friends')], default='Participant', max_length=10)),
                ('connection', models.ManyToManyField(to='CLC_FASD.Connections')),
                ('medication', models.ManyToManyField(to='CLC_FASD.Medication')),
            ],
        ),
    ]
