# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLC_FASD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(default='0mg', max_length=20),
        ),
    ]
